### ISSUE TITLE
Data in multiomics_features.tsv is incompatible

### ISSUE THREAD

**Issue by ys08** [schulter/EMOGI#3]
Hello, does `multiomics_features.tsv` contains the node feature matrix? I wonder why the data has no cnv feature and only 15 cancer types instead of 16 per mf/meth/ge.:smiley:

**Comment by schulter** [comment]
Hi,
thanks for your interst in our work. You're right the data is actually not correct. Sorry for the delay. I just pushed the correct multi-omics features for CPDB. Remember that you can also download the model and read the features from the HDF5 container.
All the best,
Roman

**Comment by hafsaumme** [comment]
Hi, May I have your raw data for breast cancer for gene expression, methylation, snv and cna? and also could you please provide input data matrix for this cancer so that we can see how look like the feature matrix, also an example of adjacency matrix?
